### ISSUE TITLE
win11的电脑直接闪退了好像

### ISSUE THREAD

**Issue by cat881223** [xiaorui16888/DingDongHelper#2]

**Comment by xiaorui16888** [comment]
应该是你配置的user.yml信息有错误，再核对一下user.yml里面的参数值。今天有一个网友跟你一样的情况。这里我没对异常捕捉。

同样我也是win11的电脑，所以不存在兼容性的问题。

**Comment by cat881223** [comment]
啊啊。。。我发现了。。。
Traceback (most recent call last):
  File "main.py", line 160, in <module>
  File "main.py", line 87, in getValidAddress
KeyError: 'valid_address'
[25220] Failed to execute script 'main' due to unhandled exception!
可能是我哪个配置不对，导致在getValidAddress这就没了

**Comment by xiaorui16888** [comment]
> 啊啊。。。我发现了。。。 Traceback (most recent call last): File "main.py", line 160, in File "main.py", line 87, in getValidAddress KeyError: 'valid_address' [25220] Failed to execute script 'main' due to unhandled exception! 可能是我哪个配置不对，导致在getValidAddress这就没了

你去小程序里面看一下，你有么有设置默认地址。地址一定要选中默认！
