### ISSUE TITLE
请问product在哪里获取呀

### ISSUE THREAD

**Issue by NealScx** [xiaorui16888/DingDongHelper#3]
是这里吗  也要写成JSON格式吗
![1](https://user-images.githubusercontent.com/85844254/163542598-33cd72b8-d087-4edc-b43f-33b37baa6e47.png)

**Comment by xiaorui16888** [comment]
你运行main.py，会自动获取并写入到card.yml的。具体哪里获取的，可以看代码里面。

**Comment by NealScx** [comment]
运行报错是什么原因呢                                                                                                                                                                      
```
本项目纯属学习使用，不可用作商业行为！任何违法违规造成的问题与本人无关！
Traceback (most recent call last):
  File "F:\Python\lib\site-packages\urllib3\connectionpool.py", line 700, in urlopen
    self._prepare_proxy(conn)
  File "F:\Python\lib\site-packages\urllib3\connectionpool.py", line 994, in _prepare_proxy
    conn.connect()
  File "F:\Python\lib\site-packages\urllib3\connection.py", line 364, in connect
    self.sock = conn = self._connect_tls_proxy(hostname, conn)
  File "F:\Python\lib\site-packages\urllib3\connection.py", line 499, in _connect_tls_proxy
    socket = ssl_wrap_socket(
  File "F:\Python\lib\site-packages\urllib3\util\ssl_.py", line 453, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(sock, context, tls_in_tls)
  File "F:\Python\lib\site-packages\urllib3\util\ssl_.py", line 495, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock)
  File "F:\Python\lib\ssl.py", line 512, in wrap_socket
    return self.sslsocket_class._create(
  File "F:\Python\lib\ssl.py", line 1070, in _create
    self.do_handshake()
  File "F:\Python\lib\ssl.py", line 1341, in do_handshake
    self._sslobj.do_handshake()
FileNotFoundError: [Errno 2] No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\Python\lib\site-packages\requests\adapters.py", line 440, in send
    resp = conn.urlopen(
  File "F:\Python\lib\site-packages\urllib3\connectionpool.py", line 785, in urlopen
    retries = retries.increment(
  File "F:\Python\lib\site-packages\urllib3\util\retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='sunquan.api.ddxq.mobi', port=443): Max retries exceeded with url: /api/v1/user/address/ (Caused by ProxyError('Cannot connect to proxy.', FileNotFoundError(2, 'No such file or directory')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Neal\Desktop\DingDongHelper-main_2\DingDongHelper-main\main.py", line 174, in <module>
    getValidAddress()
  File "C:\Users\Neal\Desktop\DingDongHelper-main_2\DingDongHelper-main\main.py", line 86, in getValidAddress
    response = requests.get(url=GETUserAddressUrl, timeout=10000, headers=header, verify=False).json()
  File "F:\Python\lib\site-packages\requests\api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "F:\Python\lib\site-packages\requests\api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "F:\Python\lib\site-packages\requests\sessions.py", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File "F:\Python\lib\site-packages\requests\sessions.py", line 645, in send
    r = adapter.send(request, **kwargs)
  File "F:\Python\lib\site-packages\requests\adapters.py", line 513, in send
    raise ProxyError(e, request=request)
requests.exceptions.ProxyError: HTTPSConnectionPool(host='sunquan.api.ddxq.mobi', port=443): Max retries exceeded with url: /api/v1/user/address/ (Caused by ProxyError('Cannot connect to proxy.', FileNotFoundError(2, 'No such file or directory')))
```

**Comment by xiaorui16888** [comment]
> 运行报错是什么原因呢
> 
> ```
> 本项目纯属学习使用，不可用作商业行为！任何违法违规造成的问题与本人无关！
> Traceback (most recent call last):
>   File "F:\Python\lib\site-packages\urllib3\connectionpool.py", line 700, in urlopen
>     self._prepare_proxy(conn)
>   File "F:\Python\lib\site-packages\urllib3\connectionpool.py", line 994, in _prepare_proxy
>     conn.connect()
>   File "F:\Python\lib\site-packages\urllib3\connection.py", line 364, in connect
>     self.sock = conn = self._connect_tls_proxy(hostname, conn)
>   File "F:\Python\lib\site-packages\urllib3\connection.py", line 499, in _connect_tls_proxy
>     socket = ssl_wrap_socket(
>   File "F:\Python\lib\site-packages\urllib3\util\ssl_.py", line 453, in ssl_wrap_socket
>     ssl_sock = _ssl_wrap_socket_impl(sock, context, tls_in_tls)
>   File "F:\Python\lib\site-packages\urllib3\util\ssl_.py", line 495, in _ssl_wrap_socket_impl
>     return ssl_context.wrap_socket(sock)
>   File "F:\Python\lib\ssl.py", line 512, in wrap_socket
>     return self.sslsocket_class._create(
>   File "F:\Python\lib\ssl.py", line 1070, in _create
>     self.do_handshake()
>   File "F:\Python\lib\ssl.py", line 1341, in do_handshake
>     self._sslobj.do_handshake()
> FileNotFoundError: [Errno 2] No such file or directory
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "F:\Python\lib\site-packages\requests\adapters.py", line 440, in send
>     resp = conn.urlopen(
>   File "F:\Python\lib\site-packages\urllib3\connectionpool.py", line 785, in urlopen
>     retries = retries.increment(
>   File "F:\Python\lib\site-packages\urllib3\util\retry.py", line 592, in increment
>     raise MaxRetryError(_pool, url, error or ResponseError(cause))
> urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='sunquan.api.ddxq.mobi', port=443): Max retries exceeded with url: /api/v1/user/address/ (Caused by ProxyError('Cannot connect to proxy.', FileNotFoundError(2, 'No such file or directory')))
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "C:\Users\Neal\Desktop\DingDongHelper-main_2\DingDongHelper-main\main.py", line 174, in <module>
>     getValidAddress()
>   File "C:\Users\Neal\Desktop\DingDongHelper-main_2\DingDongHelper-main\main.py", line 86, in getValidAddress
>     response = requests.get(url=GETUserAddressUrl, timeout=10000, headers=header, verify=False).json()
>   File "F:\Python\lib\site-packages\requests\api.py", line 75, in get
>     return request('get', url, params=params, **kwargs)
>   File "F:\Python\lib\site-packages\requests\api.py", line 61, in request
>     return session.request(method=method, url=url, **kwargs)
>   File "F:\Python\lib\site-packages\requests\sessions.py", line 529, in request
>     resp = self.send(prep, **send_kwargs)
>   File "F:\Python\lib\site-packages\requests\sessions.py", line 645, in send
>     r = adapter.send(request, **kwargs)
>   File "F:\Python\lib\site-packages\requests\adapters.py", line 513, in send
>     raise ProxyError(e, request=request)
> requests.exceptions.ProxyError: HTTPSConnectionPool(host='sunquan.api.ddxq.mobi', port=443): Max retries exceeded with url: /api/v1/user/address/ (Caused by ProxyError('Cannot connect to proxy.', FileNotFoundError(2, 'No such file or directory')))
> ```

看下你电脑是不是开加速器（vpn）了，如果开了，关闭后就可以运行。
